site_name: py-img-processor
repo_url: https://github.com/skylerhu/py-img-processor
docs_dir: .

theme:
  name: material
  palette:
    scheme: default
  features:
    - navigation.tabs

nav:
  - Home: README.md
  - Reference: docs/Reference.md
  - Changelog: docs/CHANGELOG-1.x.md
  - Contributing: docs/CONTRIBUTING.md

extra_javascript:
  - docs/js/lang-redirect.js

plugins:
  - same-dir
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 中文
          build: true
          nav_translations:
            Home: 首页
            Reference: 图像处理参数
            Changelog: 更新日志
            Contributing: 贡献者指南
